---
- name: Running workload tasks
  when: ACTION | default('provision') in ['provision', 'create']
  ansible.builtin.include_tasks: workload.yml

- name: Running workload removal tasks
  when: ACTION | default('provision') in ['remove', 'destroy']
  ansible.builtin.include_tasks: remove_workload.yml
