---
- name: Get MachineSets
  kubernetes.core.k8s_info:
    api_version: machine.openshift.io/v1beta1
    kind: MachineSet
    namespace: openshift-machine-api
  register: r_get_machinesets

- name: Set _ocp4_workload_machinesets_base_worker_machinesets
  ansible.builtin.set_fact:
    _ocp4_workload_machinesets_current_machinesets: >-
      {{ r_get_machinesets.resources }}
    _ocp4_workload_machinesets_current_machineset_names: >-
      {{ r_get_machinesets.resources
       | json_query('[].metadata.name')
      }}
    _ocp4_workload_machinesets_base_worker_machinesets: >-
      {{ r_get_machinesets.resources
       | json_query(base_worker_machineset_json_query)
      }}
  vars:
    # Base worker machinesets will lack machineset group label
    base_worker_machineset_json_query: >-
      [?!contains(keys(metadata.labels), '{{ ocp4_machineset_config_group_label }}')]

- name: Print current MachineSets
  ansible.builtin.debug:
    var: _ocp4_workload_machinesets_current_machineset_names

- name: Set cluster facts
  ansible.builtin.set_fact:
    cluster_label: >-
      {{ reference_machineset.metadata.labels['machine.openshift.io/cluster-api-cluster'] }}
    cloud_provider_api_version: >-
      {{ reference_provider_spec_value.apiVersion }}
    cloud_provider_platform: >-
      {{ reference_provider_spec_value.kind
       | regex_replace('MachineProviderConfig', '')
       | lower
      }}
  vars:
    reference_machineset: >-
      {{ _ocp4_workload_machinesets_base_worker_machinesets[0] }}
    reference_provider_spec_value: >-
      {{ reference_machineset.spec.template.spec.providerSpec.value }}

- name: Debug cluster facts
  ansible.builtin.debug:
    msg: "{{ item.label }}: {{ item.value }}"
  loop:
  - label: "Cluster Label"
    value: "{{ cluster_label }}"
  - label: "Cloud Provider API Version"
    value: "{{ cloud_provider_api_version }}"
  - label: "Cloud Provider Platform"
    value: "{{ cloud_provider_platform }}"
