---
galaxy_info:
  author: Tyrell Reddy
  description: Create tenant-specific GPU machineset for on-demand GPU provisioning
  company: Red Hat

  license: GPL-3.0-or-later

  min_ansible_version: "2.15"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - openshift
    - gpu
    - machineset
    - tenant

dependencies: []
